### ISSUE TITLE
js_include directive deprecated in njs 0.7.1

### ISSUE THREAD

**Issue by mariamatthews** [TuxInvader/nginx-dns#14]
Since njs 0.7.1 update, code part of:

``` JavaScript
  # Include the NJS module
  js_include /etc/nginx/njs.d/nginx_stream.js;
```
will no longer work. Could the code be updated to use `js_import` instead?

------------------------
Source: [https://nginx.org/en/docs/njs/changes.html#njs0.7.1](https://nginx.org/en/docs/njs/changes.html#njs0.7.1)
Source 2: [https://nginx.org/en/docs/http/ngx_http_js_module.html#js_import](https://nginx.org/en/docs/http/ngx_http_js_module.html#js_import)

**Comment by cookiemonsteruk** [comment]
I'm glad I saw this. I am on version 0.7.1 of njs on ubuntu.
Replacing js_import for js_include solved my nginx config test failure.
I now have one with `export statement is required in nginx_stream.js:55` which currently reads    ` js_preread dns_preread_dns_request;`
I'm currently trying to use nginx-dns-routing.conf for testing and trying to get over these issues.
Any ideas what I need to do?

**Comment by cookiemonsteruk** [comment]
From this explanation regarding export statement  [](https://github.com/nginx/njs/issues/121) it appears to my untrained eyes that export statement is needed in njs.d/nginx_stream.js @mariamatthews  @TuxInvader 
As a test I did add the following line below `import dns from './dns/dns.js';`
`export default {dns_get_qname, dns_get_response};`
just to test if nginx config stopped complaining and it did.
However I don't know if these are the only ones or actually the ones functions that need exporting back.
Do I need do do this/something else to get it working?
p.s. I'm not a developer, only a user trying to get an nginx gateway working for DoT.

**Comment by TuxInvader** [comment]
Hi @mariamatthews 

Thanks for raising this.... I think this deprecation has caught a few NJS projects out. 18 months just isn't long enough for some people ;-)

I'll update the code and examples to start using import rather than include. The include file was just a wrapper to import functions from libraries anyway.  The fix is simple enough......

Replace:
```
js_include /etc/nginx/njs.d/nginx_stream.js;
``` 
with: 
```
js_import /etc/nginx/njs.d/dns/dns.js;
```

Then rename the functions from  `dns_` to `dns.` Eg: use `dns.filter_doh_request` instead of `dns_filter_doh_request`

Cheers

**Comment by cookiemonsteruk** [comment]
Right, got it ! . To clarify though, this bit @TuxInvader :
`Then rename the functions from dns_ to dns. Eg: use dns.filter_doh_request instead of dns_filter_doh_request`
Is that in /etc/nginx/njs.d/nginx_stream.js ?
Pretty sure is the only place I can see them but I don't want to make assumptions.

**Comment by TuxInvader** [comment]
Hi @cookiemonsteruk 

Make the changes inside your nginx.conf.

Instead of importing `njs.d/nginx_stream.js` you want to import `njs.d/dns/dns.js` and then where you use the `dns_get_qname` change it to `dns.get_qname` and repeat for any other functions you use. So you don't need nginx_stream.js in your life anymore :-)

**Comment by cookiemonsteruk** [comment]
Thanks again. I've got an error in nginx config test after previous comment but before your last one. I'll open a new issue if it persists after this and leave this one less cluttered.

**Comment by TuxInvader** [comment]
Hi @mariamatthews - All the examples should be updated now to use js_import.

Thanks

**Comment by mariamatthews** [comment]
Thank you @TuxInvader & @cookiemonsteruk  💕 You guys rock :)
